



default: &default
 adapter: postgresql
 encoding: unicode
 username: postgres
 password: postgres
 host: localhost
 port: 5432
development:
 <<: *default
 database: project_ror
test:
 <<: *default
 database: project_ror
production:
 <<: *default
 database: project_ror
